NAME BUTTONS

PUBLIC READ_BUTTONS
PUBLIC BUTTON_STATE1
PUBLIC BUTTON_STATE2

BUTTON_STATE1 DATA 40H
BUTTON_STATE2 DATA 41H

UP_BTN      BIT P1.0
DOWN_BTN    BIT P1.1
LEFT_BTN    BIT P1.2
RIGHT_BTN   BIT P1.3

A_BTN       BIT P1.4
B_BTN       BIT P1.5
X_BTN       BIT P1.6
Y_BTN       BIT P1.7

L1_BTN      BIT P2.0
R1_BTN      BIT P2.1
L2_BTN      BIT P2.2
R2_BTN      BIT P2.3

START_BTN   BIT P2.4
SELECT_BTN  BIT P2.5
HOME_BTN    BIT P2.6

READ_BUTTONS:

    MOV BUTTON_STATE1, #00H
    MOV BUTTON_STATE2, #00H

CHECK_UP:
    JB UP_BTN, CHECK_DOWN
    ORL BUTTON_STATE1, #01H

CHECK_DOWN:
    JB DOWN_BTN, CHECK_LEFT
    ORL BUTTON_STATE1, #02H

CHECK_LEFT:
    JB LEFT_BTN, CHECK_RIGHT
    ORL BUTTON_STATE1, #04H

CHECK_RIGHT:
    JB RIGHT_BTN, CHECK_A
    ORL BUTTON_STATE1, #08H

CHECK_A:
    JB A_BTN, CHECK_B
    ORL BUTTON_STATE1, #10H

CHECK_B:
    JB B_BTN, CHECK_X
    ORL BUTTON_STATE1, #20H

CHECK_X:
    JB X_BTN, CHECK_Y
    ORL BUTTON_STATE1, #40H

CHECK_Y:
    JB Y_BTN, CHECK_L1
    ORL BUTTON_STATE1, #80H

CHECK_L1:
    JB L1_BTN, CHECK_R1
    ORL BUTTON_STATE2, #01H

CHECK_R1:
    JB R1_BTN, CHECK_L2
    ORL BUTTON_STATE2, #02H

CHECK_L2:
    JB L2_BTN, CHECK_R2
    ORL BUTTON_STATE2, #04H

CHECK_R2:
    JB R2_BTN, CHECK_START
    ORL BUTTON_STATE2, #08H

CHECK_START:
    JB START_BTN, CHECK_SELECT
    ORL BUTTON_STATE2, #10H

CHECK_SELECT:
    JB SELECT_BTN, CHECK_HOME
    ORL BUTTON_STATE2, #20H

CHECK_HOME:
    JB HOME_BTN, EXIT_BUTTONS
    ORL BUTTON_STATE2, #40H

EXIT_BUTTONS:
    RET
